{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "webapp-chart-name" . }}-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "webapp-chart-name" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: app-env
      remoteRef:
        key: {{ .Values.externalSecret.secretKey }}
{{- end }}