apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-chart-name" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "webapp.labels" . | nindent 4 }}