replicaCount: 2

image:
  repository: ghcr.io/<YOUR_GH_ORG>/<APP_NAME>
  pullPolicy: IfNotPresent
  # -- Full image tag (e.g. "1.2.3" or Git SHA). CI replaces this via --set image.tag.
  tag: "1.0.0"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  linkerd.io/inject: enabled

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  port: 80
  targetPort: http
  annotations: {}

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-cert
      hosts:
        - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

configmap:
  enabled: false
  data: {}

externalSecret:
  enabled: true
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  secretKey: "MYAPP_PROD"

pdb:
  enabled: true
  minAvailable: 1